config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  resources :jobs

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :company, presence: true
  validates :views, :salary, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, except: [ :index, :new, :create ]

  def find_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :company, :salary, :location, :start)
  end

  def index
    @jobs = Job.all
  end

  def show
    @job.increment!(:views)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.create(job_params)
    redirect_to job_url(@job), notice: 'Job Created'
  end

  def edit; end

  def update
    @job.update_attributes(job_params)
    redirect_to job_path(@job), notice: 'Job Updated!'
  end

  def destroy
    @job.destroy
    redirect_to jobs_path, notice: 'Job Deleted'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def index
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/edit.html.erb
<h1> Edit an existing job posting: </h1>

<p> Job title: </p>
<%= form_for @job do |form| %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>
<!--

<table class="show">
  <tr>
    <th>Job Title</th>
    <td><%= link_to(@job.title, job_path(@job)) %></td>
  </tr>
  <tr>
    <th>Company</th>
    <td><%= @job.company %></td>
  </tr>
  <tr>
    <th>Salary</th>
    <td><%= number_to_currency(@job[:salary]) %></td>
  </tr>
  <tr>
    <th>Views</th>
    <td><%= @job.views %></td>
  </tr>
</table>

<div class="edit_delete">
  <%= link_to "Edit", edit_job_path(@job), class: "btn1" %>
  <%= link_to "Delete", job_path(@job), method: :delete, class: "btn2", data: { confirm: "Are you sure?" } %>
</div>

<%= link_to "Return to All Job Listings", jobs_path, class: "button" %> -->

app/views/jobs/index.html.erb
<h1>All Job Listings</h1>

  <table class="index">
    <colgroup>
      <col class="title">
      <col class="company">
      <col class="salary">
    </colgroup>
    <tr>
      <th>Job Title</th>
      <th>Company</th>
      <th>Salary</th>
    </tr>

    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to(job.title, job_path(job)) %></td>
        <td><%= job.company %></td>
        <td><%= number_to_currency(job.salary) %></td>
      </tr>
    <% end %>
  </table>

<%= link_to "Create a new job", new_job_path, class: "button" %>

app/views/jobs/new.html.erb
<h1> Create a new Job posting: </h1>

<p> Job title: </p>
<%= form_for @job do |form| %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

app/views/jobs/show.html.erb
<h1> Job Details </h1>

<table class="show">
  <tr>
    <th>Job Title</th>
    <td><%= link_to(@job.title, job_path(@job)) %></td>
  </tr>
  <tr>
    <th>Company</th>
    <td><%= @job.company %></td>
  </tr>
  <tr>
    <th>Salary</th>
    <td><%= number_to_currency(@job[:salary]) %></td>
  </tr>
  <tr>
    <th>Views</th>
    <td><%= @job.views %></td>
  </tr>
</table>

<div class="edit_delete">
  <%= link_to "Edit", edit_job_path(@job), class: "btn1" %>
  <%= link_to "Delete", job_path(@job), method: :delete, class: "btn2", data: { confirm: "Are you sure?" } %>
</div>

<%= link_to "Return to All Job Listings", jobs_path, class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <div id="flash">
    <span><%= flash[:notice] %></span>
  </div>
<% end %>

<%= yield %>

</body>
</html>